name: Modify chart.py daily

on:
  schedule:
    - cron: '0 0 * * *'  # This runs once a day at midnight

jobs:
  modify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Modify chart.py
      run: echo "# Random change $(date)" >> chart.py

    - name: Set up Git user
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        
    - name: Commit and push
      run: |
        git add chart.py
        git commit -m "Modify chart.py [skip ci]" 
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GOD_PAT }}  # Assuming you've stored your PAT as a secret named PAT
