name: Modify chart.py daily

on:
  schedule:
    - cron: '0 0 * * *'  # This runs once a day at midnight

jobs:
  modify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Modify chart.py
      run: echo "# Random change $(date)" >> chart.py

    - name: Commit and push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add chart.py
        git commit -m "Modify chart.py [skip ci]" 
        git push
